# *****************************
# *  GUI settings : settings  *
# *****************************

# PlaceholderAPI support for gui title and custom items titles/lores
# ItemsAdder support for material and custom_model_data
# Make sure the slot is between 0 and (rows-count * 9)
# Materials : https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
# Don't forget to enable custom_model_data if you're using it

gui-title: "Settings: %name%"
rows: 6

custom_items: {}
  # example_item:
    # title: "§aThis is an example item!"
    # lore: "§fline 1\n§byou can put differents lines!\n§dline 3\n§cDisable this item in guis/settings.yml"
    # slot: 45
    # material: DIAMOND_SWORD
    # custom_model_data: false
    # custom_model_data_value: 0
    # action: "RIGHT:CMD:CONSOLE:say i clicked on the example item!"

items:

  # /!\ DON'T CHANGE NAME OF ITEMS (like "my-claims")

  # Bottom items
  define-loc:
    slot: 45
    material: ENDER_PEARL
    custom_model_data: false
    custom_model_data_value: 0
  define-name:
    slot: 46
    material: WRITABLE_BOOK
    custom_model_data: false
    custom_model_data_value: 0
  manage-members:
    slot: 47
    material: PAPER
    custom_model_data: false
    custom_model_data_value: 0
  manage-bans:
    slot: 48
    material: BARRIER
    custom_model_data: false
    custom_model_data_value: 0
  my-claims:
    slot: 52
    material: OAK_SIGN
    custom_model_data: false
    custom_model_data_value: 0
  apply-all-claims:
    slot: 53
    material: GREEN_CONCRETE_POWDER
    custom_model_data: false
    custom_model_data_value: 0

  # Perms items
  Build:
    slot: 1
    material: STONE
    custom_model_data: false
    custom_model_data_value: 0
  Destroy:
    slot: 2
    material: NETHERITE_PICKAXE
    custom_model_data: false
    custom_model_data_value: 0
  Buttons:
    slot: 3
    material: STONE_BUTTON
    custom_model_data: false
    custom_model_data_value: 0
  Items:
    slot: 4
    material: GLOWSTONE_DUST
    custom_model_data: false
    custom_model_data_value: 0
  InteractBlocks:
    slot: 5
    material: CHEST
    custom_model_data: false
    custom_model_data_value: 0
  Levers:
    slot: 6
    material: LEVER
    custom_model_data: false
    custom_model_data_value: 0
  Plates:
    slot: 7
    material: STONE_PRESSURE_PLATE
    custom_model_data: false
    custom_model_data_value: 0
  Doors:
    slot: 10
    material: OAK_DOOR
    custom_model_data: false
    custom_model_data_value: 0
  Trapdoors:
    slot: 11
    material: OAK_TRAPDOOR
    custom_model_data: false
    custom_model_data_value: 0
  Fencegates:
    slot: 12
    material: OAK_FENCE_GATE
    custom_model_data: false
    custom_model_data_value: 0
  Tripwires:
    slot: 13
    material: TRIPWIRE_HOOK
    custom_model_data: false
    custom_model_data_value: 0
  RepeatersComparators:
    slot: 14
    material: REPEATER
    custom_model_data: false
    custom_model_data_value: 0
  Bells:
    slot: 15
    material: BELL
    custom_model_data: false
    custom_model_data_value: 0
  Entities:
    slot: 16
    material: ARMOR_STAND
    custom_model_data: false
    custom_model_data_value: 0
  Explosions:
    slot: 19
    material: TNT
    custom_model_data: false
    custom_model_data_value: 0
  Liquids:
    slot: 20
    material: WATER_BUCKET
    custom_model_data: false
    custom_model_data_value: 0
  Redstone:
    slot: 21
    material: REDSTONE
    custom_model_data: false
    custom_model_data_value: 0
  Frostwalker:
    slot: 22
    material: DIAMOND_BOOTS
    custom_model_data: false
    custom_model_data_value: 0
  Firespread:
    slot: 23
    material: CAMPFIRE
    custom_model_data: false
    custom_model_data_value: 0
  Teleportations:
    slot: 24
    material: ENDER_PEARL
    custom_model_data: false
    custom_model_data_value: 0
  Damages:
    slot: 25
    material: APPLE
    custom_model_data: false
    custom_model_data_value: 0
  Monsters:
    slot: 29
    material: STRING
    custom_model_data: false
    custom_model_data_value: 0
  Visitors:
    slot: 30
    material: PLAYER_HEAD
    custom_model_data: false
    custom_model_data_value: 0
  Pvp:
    slot: 32
    material: IRON_SWORD
    custom_model_data: false
    custom_model_data_value: 0
  Weather:
    slot: 33
    material: SNOWBALL
    custom_model_data: false
    custom_model_data_value: 0